---
version: "2"

services:
  movieservice:
    build: .
    container_name: movie_app
    depends_on:
        - mongodbservice
#        - redisservice
    volumes:
       - .:/var/www/movieservice
    ports:
      - "5001:5001"
    expose:
      - "5001"
    restart:  always
  mongodbservice:
    image: mongo
    container_name: mongodb_container
    ports:
      - "27017:27017"
    expose:
      - "27017"
    restart:  always
#  redisservice:
#    image: redis:alpine
#    container_name: redis-servre_container
#    ports:
#      - "6379:6379"
#    expose:
#      - "6379"
#    restart:  always



